spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9101
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**,/products-category/**
          filters:
            - name: CircuitBreaker
              args:
                name: product-service
                fallbackUri: forward:/productFallback

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**,/items/**
          filters:
            - name: CircuitBreaker
              args:
                name: order-service
                fallbackUri: forward:/orderFallback
server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: "*"