spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9101
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**,/api/product-category/**
          filters:
            - name: CircuitBreaker
              args:
                name: product-service
                fallbackUri: forward:/productFallback

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**,/items/**
          filters:
            - name: CircuitBreaker
              args:
                name: order-service
                fallbackUri: forward:/orderFallback
server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: "*"